### ISSUE TITLE
Recherche mais ne trouve pas

### ISSUE THREAD

**Issue by jurnet** [geraldgg/CouchPotato-t411-custom_plugin#1]
Bonjour,
Je suis en train de tester votre projet.
Je pars sur une recherche tel que: 
- Cité des anges (uniquement T411)
- Avengers 2015 (T411 et Cpasbien)
- Spy (uniquement Cpasbien)
- La dame en noir 2

Cité des anges OK
Avengers n'affiche que t411
Spy ne le trouve pas (car peut etre en webrip ?)
la dame en noir le trouve sur t411 comme ceci The Woman in Black 2 alors qu'il y a plus de seeder avec La dame en noir 2 -> comment faire pour qu'il recherche exactement le titre donnée ?

**Comment by geraldgg** [comment]
Le ticket est un peu vieux, donc ça a peut être bougé, mais la recherche se fait effectivement sur le titre anglais en général, après une normalisation via imdb. Je pense aussi qu'une recherche avec le titre français donnerait de meilleurs résultats, en tout cas pour des recherches en langue française. Je vais voir si je peux arranger ça.

**Comment by geraldgg** [comment]
A voir si ça fonctionne mieux, une deuxième recherche est lancée avec le titre entré si la première recherche ne donne rien.
