### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by blablanumerodeux** [geraldgg/CouchPotato-t411-custom_plugin#13]
Hello, 
I follow the installation process but nothing happens after a reboot. 
There is nothing on the logs too...
Can you help me plz, 
Thanks by advance.

**Comment by blablanumerodeux** [comment]
Okay,
Sorry for this issue,
I tryed to put the plugins on ~/.Couchpotato/custom_plugins and that worked ! 
But now I can't santch any torrent from T411. With CpasBien it's working well...
Why ?

**Comment by geraldgg** [comment]
Do you have an account on T411? Did you put correct informations?

**Comment by blablanumerodeux** [comment]
Yes of course,
I tryed with this plugin : https://github.com/cocazoulou/couchpotato.provider.t411
And it's working perfectly.
