### ISSUE TITLE
error with cpasbien provider

### ISSUE THREAD

**Issue by lucasevabou14** [geraldgg/CouchPotato-t411-custom_plugin#4]
Hi , I'am encountering the following error when try to connect to cpasbien.io provider:

<addr>
11-29 13:24:22 ERROR
[ couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last): File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/couchpotato/core/event.py", line 15, in runHandler return handler(_args, *_kwargs) File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2/couchpotato/core/media/_base/providers/base.py", line 227, in search self._search(media, quality, results) File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config/custom_plugins/cpasbien/main.py", line 63, in _search data = urllib2.urlopen(req ) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 437, in open response = meth(req, response) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 550, in http_response 'http', request, response, code, msg, hdrs) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 475, in error return self._call_chain(_args) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 409, in _call_chain result = func(_args) File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 558, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) HTTPError: HTTP Error 503: Service Temporarily Unavailable encoding=UTF-8 debug=False args=['--data_dir', '/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config', '--daemon', '--pid_file', '/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config/couchpotato.pid'] app_dir=/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/CouchPotato2 data_dir=/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config desktop=None options=Namespace(config_file='/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config/settings.conf', console_log=False, daemon=True, data_dir='/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config', debug=False, pid_file='/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config/couchpotato.pid', quiet=False)
</addr>

**Comment by lucasevabou14** [comment]
ok it was an error on my side, network error,

But I steel have an issue in the code  
12-01 10:50:04 ERROR
[ cpasbien] Failed parsing cPASbien: Traceback (most recent call last): File "/share/CACHEDEV1_DATA/.qpkg/CouchPotato2/config/custom_plugins/cpasbien/main.py", line 116, in _search new['size'] = self.parseSize(str(size)) UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 8: ordinal not in range(128)

Thanks in advance for your feedback

**Comment by Lethtel** [comment]
English : 
Got the same error, i just went in main.py using notepad++ and deleted line 116.
It can't get file size, but at least it get something.
Still can't download torrent files.
Hoping for a fix too =/

Francais : 
Même erreur ici, j'ai supprimé la ligne 116 du coup il ne récupère plus les tailles des fichiers, mais il récupère des résultats.
Il ne télécharge pas les .torrents cependant.
Espérant avoir un fix rapidement.

**Comment by xila76** [comment]
@Lethtel je pense qu'au lieu de supprimer la ligne faudrait trouver le problème...

pour ma part j'ai la même chose malgré l'essai de l'ajout de ".decode('utf-8')" en fin de ligne 119 (chez moi c'est pas la 116... bizarre...)

### Information:

Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 89fd4e11 (2016-01-24 10:42:44)
Running on: ...

### Logs:

```
02-07 17:27:24 ERROR [                 cpasbien] Failed parsing cPASbien: Traceback (most recent call last):
  File "/home/xxx/CouchPotatoServer/custom_plugins/cpasbien/main.py", line 119, in _search
    new['size'] = self.parseSize(str(size).decode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 8: ordinal not in range(128)

```

**Comment by geraldgg** [comment]
I'm going to check that. Do you remember what movie you were searching?

**Comment by geraldgg** [comment]
I fixed some errors I've found, it should be better now, let me know.

**Comment by hylyah** [comment]
Same error with the last version.
