### ISSUE TITLE
Problème avec certains films seulement

### ISSUE THREAD

**Issue by thenamelessthing** [geraldgg/CouchPotato-t411-custom_plugin#5]
Avec certains films tout fonctionne bien et d'autres dont celui-ci ça donne cette errreur..

01-20 21:49:59 ERROR
[o.core.downloaders.deluge] Failed to add torrent file The.Revenant.2009.MULTi.720p.BluRay.DTS.x264-ATeR french.torrent: not a valid bencoded string Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/downloaders/deluge.py", line 255, in add_torrent_file torrent_id = self._check_torrent(False, torrent) File "/opt/couchpotato/couchpotato/core/downloaders/deluge.py", line 319, in _check_torrent info = bdecode(torrent)["info"] File "/opt/couchpotato/libs/bencode/__init__.py", line 68, in bdecode raise BTFailure("not a valid bencoded string") BTFailure: not a valid bencoded string
01-20 21:49:59 ERROR
[o.core.downloaders.deluge] Failed sending torrent to Deluge

**Comment by geraldgg** [comment]
Ca ne ressemble pas à un problème dans les plugins t411 ou cpasbien. Plutôt dans le coeur de couchpotato.
